src/pam-x2go.c: Mark unused function arguments as such.
 This resolves:

 pam-x2go.c:228:46: error: unused parameter 'flags' [-Werror,-Wunused-parameter]
 pam_sm_authenticate (pam_handle_t *pamh, int flags, int argc, const char **argv)
                                             ^
 pam-x2go.c:228:57: error: unused parameter 'argc' [-Werror,-Wunused-parameter]
 pam_sm_authenticate (pam_handle_t *pamh, int flags, int argc, const char **argv)
                                                        ^
 pam-x2go.c:228:76: error: unused parameter 'argv' [-Werror,-Wunused-parameter]
 pam_sm_authenticate (pam_handle_t *pamh, int flags, int argc, const char **argv)
                                                                           ^
 pam-x2go.c:293:46: error: unused parameter 'flags' [-Werror,-Wunused-parameter]
 pam_sm_open_session (pam_handle_t *pamh, int flags, int argc, const char ** argv)
                                             ^
 pam-x2go.c:293:57: error: unused parameter 'argc' [-Werror,-Wunused-parameter]
 pam_sm_open_session (pam_handle_t *pamh, int flags, int argc, const char ** argv)
                                                        ^
 pam-x2go.c:293:77: error: unused parameter 'argv' [-Werror,-Wunused-parameter]
 pam_sm_open_session (pam_handle_t *pamh, int flags, int argc, const char ** argv)
                                                                            ^
 pam-x2go.c:360:47: error: unused parameter 'flags' [-Werror,-Wunused-parameter]
 pam_sm_close_session (pam_handle_t *pamh, int flags, int argc, const char **argv)
                                              ^
 pam-x2go.c:360:58: error: unused parameter 'argc' [-Werror,-Wunused-parameter]
 pam_sm_close_session (pam_handle_t *pamh, int flags, int argc, const char **argv)
                                                         ^
 pam-x2go.c:360:77: error: unused parameter 'argv' [-Werror,-Wunused-parameter]
 pam_sm_close_session (pam_handle_t *pamh, int flags, int argc, const char **argv)
                                                                            ^
 pam-x2go.c:440:31: error: unused parameter 'pamh' [-Werror,-Wunused-parameter]
 pam_sm_setcred (pam_handle_t *pamh, int flags, int argc, const char ** argv)
                              ^
 pam-x2go.c:440:41: error: unused parameter 'flags' [-Werror,-Wunused-parameter]
 pam_sm_setcred (pam_handle_t *pamh, int flags, int argc, const char ** argv)
                                        ^
 pam-x2go.c:440:52: error: unused parameter 'argc' [-Werror,-Wunused-parameter]
 pam_sm_setcred (pam_handle_t *pamh, int flags, int argc, const char ** argv)
                                                   ^
 pam-x2go.c:440:72: error: unused parameter 'argv' [-Werror,-Wunused-parameter]
 pam_sm_setcred (pam_handle_t *pamh, int flags, int argc, const char ** argv)
                                                                       ^
 13 errors generated.