tests/mock_*.c: Mark unused function arguments as such.
 This resolves:

 mock_pam.c: In function 'fake_conv':
 mock_pam.c:24:20: error: unused parameter 'num_msg' [-Werror=unused-parameter]
    24 | int fake_conv (int num_msg, const struct pam_message **msg,
       |                ~~~~^~~~~~~
 mock_pam.c:25:39: error: unused parameter 'appdata_ptr' [-Werror=unused-parameter]
    25 |     struct pam_response **resp, void *appdata_ptr)
       |                                 ~~~~~~^~~~~~~~~~~
 cc1: all warnings being treated as errors